## OpenSearch config

volumes:
  opensearch-data:
    external: false
  dashboard-data:
    external: false


networks:
  SOCnet:
    external: true


services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx2048m
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OS_ADMIN_PASSWORD}
    networks:
      - SOCnet
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./install-plugins.sh:/usr/share/opensearch/install-plugins.sh
    command: >
      bash -c "/usr/share/opensearch/install-plugins.sh && ./opensearch-docker-entrypoint.sh"
    ulimits:
      memlock:
        soft: -1  
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-check-certificate -O /dev/null -q https://admin:${OS_ADMIN_PASSWORD}@localhost:9200 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 9G

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboard
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - SOCnet
    ports:
      - 5601:5601
    expose:
      - "5601"
    volumes:
      - dashboard-data:/usr/share/opensearch-dashboards/data
    depends_on:
      - opensearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q http://localhost:5601 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
