services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=soc-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_master_nodes=opensearch
      - action.auto_create_index:true
      - compatibility.override_main_response_version:true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 0.0.0.0:9200:9200
    networks:
      - soc-net
      - public-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 0.0.0.0:5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
    networks:
      - soc-net
      - public-net
    volumes:
      - ./config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml

volumes:
  opensearch-data1:

networks:
  soc-net:
  public-net: