list: "/tmp/targets-domain.txt"

a: true
aaaa: true
cname: true
ns: true
txt: true
srv: true
ptr: true
mx: true
soa: true

axfr: true
caa: true

# filter result by dns status code (eg. -rcode noerror,servfail,refused)
#rcode: 

# display
resp: false
#resp-only: false
cdn: true
asn: true

threads: 150
rate-limit: 1000

disable-update-check: true

output: "/tmp/OUTPUT-dnsx.jsonl"
json: true

omit-raw: true

health-check: false
silent: false
verbose: true
update: false
debug: false
stats: false
version: false
retry: 3
hostsfile: false
trace: false
resume: false
resolver: "/tmp/resolvers-dns.txt"
wildcard-threshold: 25
