list: "/tmp/targets-hosts.txt" 
resume: false
scan-all-ips: true

report-config: "/root/.config/nuclei/reporting-config.yaml"

new-templates: false
automatic-scan: false
validate: false
no-strict-syntax: false
template-display: false

leave-default-ports: false

# enable loading code protocol-based templates
#code: false
disable-unsigned-templates: true

# templates to run based on severity. possible values: info, low, medium, high, critical, unknown
severity:
  - critical
  - high
  - medium
  - unknown
  - low
  - info
#exclude-severity:
#  - info
#  - low
#  - unknown

type:
  - cloud
  - dns
  - file
  - http
  - javascript
  - network
exclude-type:
  - ssl
  - passive
  - code
  - dast
  - headless
  - workflows
exclude-templates:
  - http/technologies/tech-detect
  - http/fuzzing/waf-fuzz.yaml

# output file to write found issues/vulnerabilities
output: "/tmp/OUTPUT-nuclei.jsonl"
store-resp: false
#store-resp-dir: "/tmp/nuclei"
silent: false
jsonl: true
omit-raw: false

follow-redirects: false
follow-host-redirects: false
max-redirects: 3
disable-redirects: false

# custom header/cookie to include in all http request in header:value format (cli, file)
header: ["SECURITY_DEPARTMENT:SCANNING-FOR-VULNERABILITIES-CONTACT-FOR-INFORMATION"]

# file containing resolver list for nuclei
resolvers: "/tmp/resolvers-dns.txt"
disable-clustering: false
force-http2: false

# use ztls library with autofallback to standard one for tls13 [deprecated] autofallback to ztls is enabled by default
ztls: true

# keep-alive duration for network requests.
dialer-keep-alive: 5

# type of payload combinations to perform (batteringram,pitchfork,clusterbomb)
#attack-type: 

# enable / run dast (fuzz) nuclei templates
dast: false
# overrides fuzzing type set in template (replace, prefix, postfix, infix)
#fuzzing-type: 
# overrides fuzzing mode set in template (multiple, single)
#fuzzing-mode: 
display-fuzz-points: false
fuzz-param-frequency: 10
fuzz-aggression: low

# in scope url regex to be followed by fuzzer
#fuzz-scope: []

# out of scope url regex to be excluded by fuzzer
#fuzz-out-scope: []

# enable uncover engine
#uncover: false
# uncover search query
#uncover-query: []
# uncover search engine (shodan,censys,fofa,shodan-idb,quake,hunter,zoomeye,netlas,criminalip,publicwww,hunterhow,google,odin,binaryedge) (default shodan)
#uncover-engine: []
# uncover fields to return (ip,port,host)
#uncover-field: ip:port
# uncover results to return
#uncover-limit: 100
# override ratelimit of engines with unknown ratelimit (default 60 req/min)
#uncover-ratelimit: 60

# strategy to use while scanning(auto/host-spray/template-spray)
#scan-strategy: auto
scan-strategy: host-spray
#scan-strategy: template-spray

# maximum number of templates to be executed in parallel
concurrency: 20

# maximum number of hosts to be analyzed in parallel per template
bulk-size: 15

# maximum number of requests to send per second
rate-limit: 250

# maximum number of javascript runtimes to be executed in parallel
js-concurrency: 60

# max payload concurrency for each template
payload-concurrency: 10

# http probe concurrency with httpx
probe-concurrency: 750

timeout: 3
retries: 2

# disable skipping host from scan based on errors
no-mhe: false
# max errors for a host before skipping from scan
max-host-error: 25

# use a project folder to avoid sending same request multiple times
project: true
project-path: "/tmp/project/"

stop-at-first-match: false
stream: true
no-stdin: true

# disable httpx probing for non-url input
#no-httpx: false

headless: false
# maximum number of headless hosts to be analyzed in parallel per template
headless-bulk-size: 5
# maximum number of headless templates to be executed in parallel
headless-concurrency: 5
page-timeout: 5
show-browser: false
#headless-options: []
#system-chrome: false
#list-headless-action: false
#list-dsl-function: false

version: false
vv: false
debug: false
health-check: false
update-templates: false
update-template-dir: "/tmp/nuclei-templates/" 
disable-update-check: true
