#allow-list:
#  severity: []
#  tags: []
#deny-list:
#  severity: []
#  tags: []
elasticsearch:
  host: "opensearch"
  ip: "127.0.0.1"
  port: 9200
  ssl: true
  ssl-verification: false
  username: "admin"
  password: "CHANGE_ME"
  index-name: "ObiWanKenobi"
