# File containing list of targets
list: "/tmp/targets-hosts.txt"
exclude-file: "/tmp/excluded-ips.txt"
ports-file: "/tmp/excluded-ports.txt"
# top ports to scan [full,100,1000]
#top-ports: 1000
#exclude-ports: 
exclude-cdn: true
display-cdn: true

c: 300
rate: 3000

# disable automatic naabu update check
disable-update-check: true

# file to write output to (optional)
output: "/tmp/OUTPUT-naabu.jsonl"
json: true

# scan all the ip's associated with dns record
scan-all-ips: true

# type of port scan (syn/connect)
scan-type: c

nmap: false
resume: false
passive: false

# list of resolvers
r: "/tmp/resolvers-dns.txt" 

skip-host-discovery: true
with-host-discovery: false
#probe-icmp-echo: true
arp-ping: false

service-discovery: false
service-version: false
# number of retries for the port scan
retries: 1

# millisecond to wait before timing out
timeout: 2000

# ping probes for verification of host
#ping: true
verify: false
