list: "/tmp/targets-hosts.txt"
port: "/tmp/portlist-tls.txt"

# tls connection mode to use (ctls, ztls, openssl, auto)
scan-mode: "openssl"

# enable pre-handshake tls connection (early termination) using ztls
#pre-handshake: false

scan-all-ips: true

# display
san: false
cn: false
so: true
tls-version: true
cipher: true

# display certificate fingerprint hashes (md5,sha1,sha256)
hash: "sha1"

jarm: false
ja3: false
ja3s: false
wildcard-cert: true

# display tls probe status
#probe-status: false

version-enum: true
cipher-enum: true

# ciphers types to enumerate. possible values: all/secure/insecure/weak (comma-separated)
cipher-type: "all"

# include client hello in json output (ztls mode only)
client-hello: false
# include server hello in json output (ztls mode only)
server-hello: false

serial: true
expired: true
self-signed: true
mismatched: true
revoked: true
untrusted: true

resolvers:
  - 1.1.1.1
  - 9.9.9.9
  - 1.0.0.1
  - 76.223.122.150
  - 76.76.10.0
  - 149.112.112.112
  - 8.8.4.4

# perform reverse ptr to retrieve sni from ip
#rev-ptr-sni: false

# minimum tls version to accept (ssl30,tls10,tls11,tls12,tls13)
#SSL30 is non functional
min-version: "tls10"

# maximum tls version to accept (ssl30,tls10,tls11,tls12,tls13)
max-version: "tls13"

# include certificates in json output (pem format)
certificate: false

# include certificates chain in json output
tls-chain: false

# enable verification of server certificate
verify-cert: false

# openssl binary path
#openssl-binary: 

# strategy to use if encountered errors while checking revocation status
#hardfail: false

# number of concurrent threads to process
concurrency: 500

# cipher enum concurrency for each target
cipher-concurrency: 25

# tls connection timeout in seconds
timeout: 5

# number of retries to perform for failures
retry: 2

# duration to wait between each connection per thread (eg: 200ms, 1s)
#delay: 250ms

update: false
disable-update-check: false
output: "/tmp/OUTPUT-tlsx.jsonl"
json: true
dns: true

resp-only: false
silent: false
no-color: false
verbose: true
version: false
hc: false

