list: "/tmp/targets-domain.txt"

sources: ["alienvault", "anubis", "c99", "commoncrawl", "crtsh", "digitorus", "dnsdumpster", "hackertarget", "hudsonrock", "intelx", "rapiddns", "shodan", "sitedossier", "threatcrowd", "waybackarchive", "virustotal"]

recursive: true
all: false

rate-limit: 1000
t: 200
disable-update-check: true
output: "/tmp/OUTPUT-subfinder.jsonl"
json: true

active: true
ip: true

rlist: "/tmp/resolvers-dns.txt"

silent: false
version: false
verbose: true
timeout: 5

collect-sources: true