l: "/tmp/targets.txt"

# excluded hosts
#ef: "/tmp/hosts-exclude.txt"

# excluded ports
#pf: "/tmp/ports-exclude.txt"

# top ports to scan [full,100,1000]
tp: 1000

# skip full port scans for cdn/waf (only scan for port 80,443)
ec: true

# display cdn in use
cdn: true

# thread count
c: 400

# packets per sec
rate: 2500

# disable automatic naabu update check
disable-update-check: true

# file to write output to (optional)
output: "/data/OUTPUT-naabu.jsonl"
json: true

# scan all the ip's associated with dns record
sa: true

# type of port scan (syn/connect)
s: c

nmap: false

# list of custom resolver dns resolution (comma separated or from file)
r: "/tmp/resolvers-dns.txt" 

# resume scan using resume.cfg
resume: false

# display passive open ports using shodan internetdb api
#passive: true
l: "/tmp/targets.txt"

# excluded hosts
#ef: "/tmp/hosts-exclude.txt"

# excluded ports
#pf: "/tmp/ports-exclude.txt"

# top ports to scan [full,100,1000]
tp: 1000

# skip full port scans for cdn/waf (only scan for port 80,443)
ec: true

# display cdn in use
cdn: true

# thread count
c: 400

# packets per sec
rate: 2500

# disable automatic naabu update check
disable-update-check: true

# file to write output to (optional)
output: "/data/OUTPUT-naabu.jsonl"
json: true

# scan all the ip's associated with dns record
sa: true

# type of port scan (syn/connect)
s: c

nmap: false
resume: false

# list of custom resolver dns resolution (comma separated or from file)
r: "/tmp/resolvers-dns.txt" 

# skip host discovery
#skip-host-discovery: false

# enable host discovery
with-host-discovery: true

#probe-tcp-syn: []
#probe-tcp-ack: []
#probe-icmp-echo: true
arp-ping: false

service-discovery: false
service-version: false

# number of retries for the port scan
retries: 1

# millisecond to wait before timing out
timeout: 1000

# ping probes for verification of host
#ping: true

# validate the ports again with tcp verification
verify: true

# display only results in output
silent: false

# skip host discovery
#skip-host-discovery: false

# enable host discovery
with-host-discovery: true

#probe-tcp-syn: []
#probe-tcp-ack: []
#probe-icmp-echo: true
arp-ping: false

service-discovery: false
service-version: false

# number of retries for the port scan
retries: 1

# millisecond to wait before timing out
timeout: 1000

# ping probes for verification of host
#ping: true

# validate the ports again with tcp verification
verify: true

# display only results in output
silent: false
