l: "/tmp/targets.txt"

# excluded hosts
ef: "/tmp/hosts-exclude.txt"

# excluded ports
pf: "/tmp/ports-exclude.txt"

# number of retries for the port scan
retries: 1
# millisecond to wait before timing out
timeout: 1500 

# ping probes for verification of host
ping: true

# validate the ports again with tcp verification
verify: true
silent: true
# top ports to scan [full,100,1000]
tp: 1000

# skip full port scans for cdn/waf (only scan for port 80,443)
ec: false

# display cdn in use
cdn: true

# thread count
c: 500

# packets per sec
rate: 3000

# disable automatic naabu update check
disable-update-check: true

# file to write output to (optional)
output: "/data/OUTPUT-naabu.jsonl"
json: true

# scan all the ip's associated with dns record
sa: true

# ip version to scan of hostname (4,6) - (default 4)
#iv: ["4"]

# type of port scan (syn/connect)
s: c

nmap: false

# list of custom resolver dns resolution (comma separated or from file)
r: "/tmp/resolvers-dns.txt" 

# resume scan using resume.cfg
resume: false

# display passive open ports using shodan internetdb api
passive: true

# skip host discovery
#skip-host-discovery: false

# enable host discovery
with-host-discovery: true

#probe-tcp-syn: []
#probe-tcp-ack: []
#probe-icmp-echo: false
arp-ping: false

service-discovery: false
service-version: false
