list: "/tmp/targets.txt"
port: [443,8443,10443,444]

# tls connection mode to use (ctls, ztls, openssl, auto)
scan-mode: "auto"

# enable pre-handshake tls connection (early termination) using ztls
#pre-handshake: false

scan-all-ips: true

# display
san: false
cn: false
so: true
tls-version: true
cipher: true

# display certificate fingerprint hashes (md5,sha1,sha256)
hash: "sha1"

jarm: false
ja3: true
ja3s: true
wildcard-cert: true

# display tls probe status
#probe-status: false

version-enum: true
cipher-enum: true

# ciphers types to enumerate. possible values: all/secure/insecure/weak (comma-separated)
cipher-type: "all"

# include client hello in json output (ztls mode only)
client-hello: false
# include server hello in json output (ztls mode only)
server-hello: false

serial: true
expired: true
self-signed: true
mismatched: true
revoked: true
untrusted: true

resolvers: ["1.1.1.1", "8.8.4.4", "8.8.8.8"]

# perform reverse ptr to retrieve sni from ip
#rev-ptr-sni: false

# minimum tls version to accept (ssl30,tls10,tls11,tls12,tls13)
#min-version: "ssl30"

# maximum tls version to accept (ssl30,tls10,tls11,tls12,tls13)
#max-version: "tls13"

# include certificates in json output (pem format)
certificate: true

# include certificates chain in json output
tls-chain: true

# enable verification of server certificate
#verify-cert: true

# openssl binary path
#openssl-binary: 

# strategy to use if encountered errors while checking revocation status
#hardfail: false

# number of concurrent threads to process
concurrency: 150

# cipher enum concurrency for each target
cipher-concurrency: 10

# tls connection timeout in seconds
timeout: 5

# number of retries to perform for failures
retry: 2

# duration to wait between each connection per thread (eg: 200ms, 1s)
#delay: 

update: false
disable-update-check: false
output: "/data/OUTPUT-tlsx.jsonl"
json: true
dns: true

resp-only: false
silent: false
no-color: false
verbose: false
version: false
hc: false

